/**
 * @file idt.c
 * @brief IDT setup and basic interrupt dispatch for Helios.
 *
 * Installs 256 IDT entries and routes CPU exceptions to handlers
 * that report diagnostics to serial.
 */

#include <arch/x86_64/paging.h>
#include <arch/x86_64/msr.h>
#include <helios/types.h>

/* Forward declarations */
extern void serial_puts(const char *s);
extern void serial_printf(const char *fmt, ...);
extern NORETURN void panic_with_frame(const char *msg, void *frame);
extern void *memset(void *dest, int val, size_t n);

/* ═══════════════════════════════════════════════════════════════════════════
 */
/*  IDT structures                                                            */
/* ═══════════════════════════════════════════════════════════════════════════
 */

typedef struct {
  uint16_t offset_low;  /* Bits 0–15 of handler address        */
  uint16_t segment;     /* Code segment selector (0x08)        */
  uint8_t ist;          /* IST index (0 = no IST)              */
  uint8_t type_attr;    /* Gate type + DPL + present           */
  uint16_t offset_mid;  /* Bits 16–31                          */
  uint32_t offset_high; /* Bits 32–63                          */
  uint32_t _reserved;
} PACKED idt_entry_t;

_Static_assert(sizeof(idt_entry_t) == 16, "IDT entry must be 16 bytes");

typedef struct {
  uint16_t limit;
  uint64_t base;
} PACKED idt_ptr_t;

/* ═══════════════════════════════════════════════════════════════════════════
 */
/*  IDT table (256 entries)                                                   */
/* ═══════════════════════════════════════════════════════════════════════════
 */

static idt_entry_t g_idt[256];
static idt_ptr_t g_idt_ptr;

/* ═══════════════════════════════════════════════════════════════════════════
 */
/*  ISR stubs (defined in idt_stubs.asm)                                      */
/* ═══════════════════════════════════════════════════════════════════════════
 */

/* These are the 256 ISR entry points generated by the assembly macros */
extern void isr_0(void);
extern void isr_1(void);
extern void isr_2(void);
extern void isr_3(void);
extern void isr_4(void);
extern void isr_5(void);
extern void isr_6(void);
extern void isr_7(void);
extern void isr_8(void);
extern void isr_9(void);
extern void isr_10(void);
extern void isr_11(void);
extern void isr_12(void);
extern void isr_13(void);
extern void isr_14(void);
extern void isr_15(void);
extern void isr_16(void);
extern void isr_17(void);
extern void isr_18(void);
extern void isr_19(void);
extern void isr_20(void);
extern void isr_21(void);
extern void isr_22(void);
extern void isr_23(void);
extern void isr_24(void);
extern void isr_25(void);
extern void isr_26(void);
extern void isr_27(void);
extern void isr_28(void);
extern void isr_29(void);
extern void isr_30(void);
extern void isr_31(void);

/* Per-vector stub table for vectors 32–255 (generated in idt_stubs.asm) */
extern void (*isr_irq_table[])(void);

/* NX support query — defined in vmm.c */
extern bool vmm_nx_supported(void);

/* ═══════════════════════════════════════════════════════════════════════════
 */
/*  Exception names                                                           */
/* ═══════════════════════════════════════════════════════════════════════════
 */

static const char *exception_names[32] = {
    "#DE Divide Error",
    "#DB Debug",
    "NMI Non-Maskable Interrupt",
    "#BP Breakpoint",
    "#OF Overflow",
    "#BR Bound Range Exceeded",
    "#UD Invalid Opcode",
    "#NM Device Not Available",
    "#DF Double Fault",
    "Coprocessor Segment Overrun",
    "#TS Invalid TSS",
    "#NP Segment Not Present",
    "#SS Stack-Segment Fault",
    "#GP General Protection Fault",
    "#PF Page Fault",
    "(Reserved)",
    "#MF x87 FP Exception",
    "#AC Alignment Check",
    "#MC Machine Check",
    "#XM SIMD FP Exception",
    "#VE Virtualization Exception",
    "#CP Control Protection",
    "(Reserved)",
    "(Reserved)",
    "(Reserved)",
    "(Reserved)",
    "(Reserved)",
    "(Reserved)",
    "#HV Hypervisor Injection",
    "#VC VMM Communication",
    "#SX Security Exception",
    "(Reserved)",
};

/* ═══════════════════════════════════════════════════════════════════════════
 */
/*  IDT helpers                                                               */
/* ═══════════════════════════════════════════════════════════════════════════
 */

/**
 * @brief Set a single IDT entry.
 *
 * @param vector     Interrupt vector (0–255)
 * @param handler    Address of the ISR stub function
 * @param type_attr  Gate type + DPL + present (e.g. 0x8E for interrupt gate)
 * @param ist        IST index (0 = use current RSP)
 */
static void idt_set_entry(uint8_t vector, uint64_t handler, uint8_t type_attr,
                          uint8_t ist) {
  g_idt[vector].offset_low = (uint16_t)(handler & 0xFFFF);
  g_idt[vector].segment = 0x08; /* Kernel code segment */
  g_idt[vector].ist = ist & 0x07;
  g_idt[vector].type_attr = type_attr;
  g_idt[vector].offset_mid = (uint16_t)((handler >> 16) & 0xFFFF);
  g_idt[vector].offset_high = (uint32_t)((handler >> 32) & 0xFFFFFFFF);
  g_idt[vector]._reserved = 0;
}

/* ═══════════════════════════════════════════════════════════════════════════
 */
/*  Interrupt dispatch (called from isr_common in idt_stubs.asm)              */
/* ═══════════════════════════════════════════════════════════════════════════
 */

typedef struct {
  uint64_t r15, r14, r13, r12, r11, r10, r9, r8;
  uint64_t rbp, rdi, rsi, rdx, rcx, rbx, rax;
  uint64_t int_no;
  uint64_t error_code;
  uint64_t rip;
  uint64_t cs;
  uint64_t rflags;
  uint64_t rsp;
  uint64_t ss;
} PACKED interrupt_frame_t;

/* Phase 1 imports for demand paging */
extern phys_addr_t pmm_alloc_pages(uint32_t order);
extern void vmm_map_page(virt_addr_t virt, phys_addr_t phys, uint64_t flags);
extern virt_addr_t vmm_get_guard_page_addr(void);

void interrupt_dispatch(interrupt_frame_t *frame) {
  uint64_t vector = frame->int_no;

  if (vector < 32) {
    /* ── #DF Double Fault (vector 8) ─────────────────────────────────── */
    if (vector == 0x08) {
      serial_puts("\n!!! DOUBLE FAULT — unrecoverable !!!\n");
      panic_with_frame("#DF Double Fault", frame);
    }

    /* ── #GP General Protection Fault (vector 13) ────────────────────── */
    if (vector == 0x0D) {
      serial_puts("\n!!! GENERAL PROTECTION FAULT !!!\n");
      serial_printf("  RIP: 0x%016lx  CS: 0x%04lx\n", frame->rip, frame->cs);
      serial_printf("  Error code: 0x%016lx\n", frame->error_code);
      panic_with_frame("#GP General Protection Fault", frame);
    }

    /* ── #PF Page Fault (vector 14) ──────────────────────────────────── */
    if (vector == 0x0E) {
      uint64_t fault_addr = read_cr2();
      uint64_t error_code = frame->error_code;

      /* Check 0: User-mode fault — no micro-program infrastructure yet.
       * Any #PF from Ring 3 before Phase 2 is unconditionally fatal.
       * Phase 2 will replace this with a proper capability-aware handler. */
      if (error_code & PF_USER) {
        serial_puts(
            "\n!!! USER-MODE PAGE FAULT (no micro-program handler) !!!\n");
        serial_printf("  Faulting address: 0x%016lx\n", fault_addr);
        serial_printf("  Error code:       0x%016lx\n", error_code);
        serial_printf("  RIP: 0x%016lx  CS: 0x%04lx\n", frame->rip, frame->cs);
        panic_with_frame(
            "#PF from user mode before micro-program infrastructure", frame);
      }

      /* Check 1: Guard page below kernel stack → stack overflow */
      virt_addr_t guard = vmm_get_guard_page_addr();
      if (guard != 0 && fault_addr >= guard && fault_addr < guard + PAGE_SIZE) {
        serial_puts("\n!!! KERNEL STACK OVERFLOW !!!\n");
        serial_printf("  Faulting address: 0x%016lx (guard page)\n",
                      fault_addr);
        panic_with_frame("kernel stack overflow", frame);
      }

      /* Check 2: Demand paging for kernel heap region
       * [KERNEL_HEAP_BASE, KERNEL_HEAP_BASE + 1 GiB)
       * Only if the page is NOT present (error_code bit 0 = 0) */
      if (!(error_code & PF_PRESENT) && fault_addr >= KERNEL_HEAP_BASE &&
          fault_addr < KERNEL_VMA) {
        phys_addr_t p = pmm_alloc_pages(0);
        if (p == 0) {
          serial_puts("\n!!! OUT OF MEMORY on demand page !!!\n");
          panic_with_frame("OOM on demand page", frame);
        }
        vmm_map_page(fault_addr & PAGE_MASK, p,
                     PTE_PRESENT | PTE_WRITABLE |
                     (vmm_nx_supported() ? PTE_NO_EXECUTE : 0));
        return; /* Retry the faulting instruction */
      }

      /* Check 3: Generic page fault — print full details and panic */
      serial_puts("\n!!! PAGE FAULT !!!\n");
      serial_printf("  Faulting address: 0x%016lx\n", fault_addr);
      serial_printf("  Error code:       0x%016lx\n", error_code);
      serial_printf("  Flags: %s %s %s %s\n",
                    (error_code & PF_PRESENT) ? "PRESENT" : "NOT_PRESENT",
                    (error_code & PF_WRITE) ? "WRITE" : "READ",
                    (error_code & PF_USER) ? "USER" : "KERNEL",
                    (error_code & PF_INSN_FETCH) ? "INSN_FETCH" : "");
      serial_printf("  RIP: 0x%016lx  CS: 0x%04lx\n", frame->rip, frame->cs);
      panic_with_frame("#PF Page Fault", frame);
    }

    /* ── All other CPU exceptions ────────────────────────────────────── */
    serial_puts("\n!!! CPU EXCEPTION !!!\n");
    serial_printf("  Vector: 0x%02x — %s\n", (unsigned int)vector,
                  exception_names[vector]);
    serial_printf("  Error code: 0x%016lx\n", frame->error_code);
    serial_printf("  RIP: 0x%016lx  CS: 0x%04lx\n", frame->rip, frame->cs);
    serial_printf("  RSP: 0x%016lx  SS: 0x%04lx\n", frame->rsp, frame->ss);
    serial_printf("  RFLAGS: 0x%016lx\n", frame->rflags);
    panic_with_frame(exception_names[vector], frame);
  }

  /* Vectors 32–255: device interrupts, timer, IPIs */

  /* Forward declarations for scheduler and APIC */
  extern bool g_scheduler_online;
  extern void scheduler_preempt(void);

  /* Local EOI helper — writes directly to x2APIC EOI MSR (0x80B).
   * We avoid including x2apic.h here since x2apic_eoi is static inline
   * and a forward declaration would create a linker-unresolved reference. */
  #define LOCAL_X2APIC_EOI() do { wrmsr(0x80B, 0); } while (0)

  /* Timer vector — APIC timer fires scheduler preemption */
  if (vector == 0x20) {
    LOCAL_X2APIC_EOI();
    if (g_scheduler_online) {
      scheduler_preempt();
    }
    return;
  }

  /* IPI vectors 0xF0–0xF3 */
  switch (vector) {
  case 0xF0:  /* IPI_RESCHEDULE */
    LOCAL_X2APIC_EOI();
    /* No action needed — the idle loop will check queues on return */
    return;

  case 0xF1:  /* IPI_TLB_SHOOTDOWN */
    LOCAL_X2APIC_EOI();
    /* Reload CR3 to flush TLB */
    write_cr3(read_cr3());
    return;

  case 0xF2:  /* IPI_HALT */
    LOCAL_X2APIC_EOI();
    cli();
    for (;;) cpu_halt();
    /* unreachable */

  case 0xF3:  /* IPI_PANIC */
    LOCAL_X2APIC_EOI();
    serial_puts("  !!! IPI PANIC received — halting core !!!\n");
    cli();
    for (;;) cpu_halt();
    /* unreachable */

  case 0xFE:  /* Spurious vector */
    /* Do NOT send EOI for spurious interrupts */
    return;

  default:
    break;
  }

  serial_printf("  Unexpected interrupt vector: 0x%02x\n",
                (unsigned int)vector);
}

/* ═══════════════════════════════════════════════════════════════════════════
 */
/*  IDT installation                                                          */
/* ═══════════════════════════════════════════════════════════════════════════
 */

/* ISR stub table — filled by isr_table_init */
typedef void (*isr_func_t)(void);

static isr_func_t isr_stubs[32] = {
    isr_0,  isr_1,  isr_2,  isr_3,  isr_4,  isr_5,  isr_6,  isr_7,
    isr_8,  isr_9,  isr_10, isr_11, isr_12, isr_13, isr_14, isr_15,
    isr_16, isr_17, isr_18, isr_19, isr_20, isr_21, isr_22, isr_23,
    isr_24, isr_25, isr_26, isr_27, isr_28, isr_29, isr_30, isr_31,
};

/**
 * @brief Install the IDT with all 256 entries.
 *
 * Vectors 0–31: CPU exception handlers with appropriate IST settings
 * Vectors 32–255: generic stub (unhandled, reports to serial)
 */
void idt_install(void) {
  /* Clear the IDT */
  memset(g_idt, 0, sizeof(g_idt));

  /* Install CPU exception handlers (vectors 0–31) */
  for (int i = 0; i < 32; i++) {
    uint8_t ist = 0;

    /* Assign dedicated stacks for critical exceptions */
    if (i == 0x08)
      ist = 1; /* Double Fault → IST 1 */
    if (i == 0x02)
      ist = 2; /* NMI → IST 2 */
    if (i == 0x12)
      ist = 3; /* Machine Check → IST 3 */
    if (i == 0x01 || i == 0x03)
      ist = 4; /* Debug exceptions → IST 4 */
    if (i == 0x0E)
      ist = 5; /* Page Fault → IST 5 — #PF is how a kernel-stack overflow
                * is first reported (the guard page below kernel_stack_bottom
                * unmaps to a #PF). Without its own IST, delivering that very
                * #PF requires pushing the exception frame onto the already-
                * overflowed stack, which either corrupts adjacent memory or
                * immediately re-faults. A dedicated stack lets the handler
                * always run on known-good memory and produce a clean panic. */

    /* 0x8E = 64-bit Interrupt Gate, DPL=0, Present */
    idt_set_entry((uint8_t)i, (uint64_t)isr_stubs[i], 0x8E, ist);
  }

  /* Install per-vector handlers for vectors 32–255 */
  for (int i = 32; i < 256; i++) {
    idt_set_entry((uint8_t)i, (uint64_t)isr_irq_table[i - 32], 0x8E, 0);
  }

  /* Load IDT */
  g_idt_ptr.limit = sizeof(g_idt) - 1;
  g_idt_ptr.base = (uint64_t)&g_idt;
  __asm__ volatile("lidt (%0)" : : "r"(&g_idt_ptr) : "memory");
}
